#!/bin/sh

# Ensure the user entered a number and that it is between 1 and 100.
if [[ -z $1 ]]; then
  echo "You must enter a number between 1 and 100."
  exit 0;
fi

# Calculate an equation (converting it to an int if a second parameter is passed).
calculate() {
  if [[ -n $2 ]]; then
    echo $(awk "BEGIN{print int($1)}")
  else
    echo $(awk "BEGIN{print $1}")
  fi
}

# Overwrite a specified file with the given value
write() {
  echo $1 | sudo tee $2
}

# Convert the given percentage to the appropriate int
brightness() {
  percent=$(calculate "$1 / 100")
  echo $(calculate "$max * $percent" true)
}

# Save the location and get the max brightness value.
location='/sys/class/backlight/intel_backlight'
max=$(cat $location/max_brightness)

# Write the new brightness level to the appropriate file and alert the user.
write $(brightness $1) $location/brightness &> /dev/null
echo "Set the screen brightness to ${1}%."