#!/bin/sh

# This script sets the Master volume (by percentage) in alsamixer.
if [[ -z $1 ]]; then
  echo "You must enter a number between 1 and 100."
  exit 0;
fi

# Set the master volume and alert the user.
amixer set Master "${1}%" &> /dev/null
echo "Set Master volume to ${1}%."
