# ~/.config/starship.toml

# Set timeout
command_timeout = 5000

# Inserts a blank line between shell prompts
add_newline = false

# Change the default prompt format
format = """$os $time \
$all$character"""

[os]
format = "$symbol"
disabled = false

[os.symbols]
Windows = "[](111)"
Ubuntu = "[](98)"
Debian = "[](221)"

# Change the default prompt characters
[character]
success_symbol = "[└──▶](98)"
error_symbol = "[└──▶](98)"

[time]
disabled = false
format = '[$time]($style)'
style = "98"
use_12hr = false
time_format = '%R'
utc_time_offset = '-5'

# Shows the username
[username]
style_user = "221"
style_root = "black bold"
format = "[$user]($style) "
show_always = false
disabled = false  # disable in powershell

[hostname]
format = "[\\(${hostname}\\)](221) "
ssh_only = true
detect_env_vars = ['!TMUX', 'SSH_CONNECTION']
disabled = false

[directory]
truncation_length = 3
truncation_symbol = "…/"
read_only_style = "197"
read_only = "  "
format = "[$path]($style)[$read_only]($read_only_style) "

[git_branch]
symbol = ""
format = "on [$symbol$branch]($style) "
truncation_length = 16
truncation_symbol = "…/"
style = "bold green"

[git_status]
disabled = true

[terraform]
format = "via [ terraform $version]($style) 壟 [$workspace]($style) "

[vagrant]
format = "via [ vagrant $version]($style) "

[docker_context]
format = "via [ $context](bold blue) "

[helm]
format = "via [ $version](bold purple) "

[python]
format ='[\(${symbol}${pyenv_prefix}(${version})(\\($virtualenv\\) )\)]($style)'
version_format = "v${major}.${minor}"
symbol = " "

[nodejs]
format = "via [ $version](bold green) "
disabled = true

[ruby]
format = "via [ $version]($style) "

[kubernetes]
format = 'on [ $context\($namespace\)](bold purple) '
disabled = false
[kubernetes.context_aliases]
"clcreative-k8s-staging" = "cl-k8s-staging"
"clcreative-k8s-production" = "cl-k8s-prod"
