#!/usr/bin/env bash

# ┌──────────────────────────────────┐
# │    Herbstluftwm Configuration    │
# └──────────────────────────────────┘


# ┌──────────────────────┐
# │    Initialization    │
# └──────────────────────┘
hc() {
  herbstclient "$@"
}

load_module() {
  local mod_script="$HOME/.config/herbstluftwm/module/$1"
  . $mod_script
}

hc emit_hook reload


# ┌──────────────────────┐
# │    Module Loading    │
# └──────────────────────┘
load_module "keybinds"
load_module "tags"
load_module "theme"
load_module "rules"

# unlock, just to be sure
hc unlock

load_module "multimonitor"
# load module "panel"
load_module "postload"