#!/bin/bash

# Restore the background
nitrogen --restore &

# Start libinput-gestures
libinput-gestures-setup start

# Set amixer pre-amp to 40%
amixer set "Pre-Amp" '40%'

# Start dunst (responsible for notifications)
pgrep dunst || dunst &

# Start the network manager applet
nm-applet

# Prevent middle mouse pasting
xmousepasteblock