#!/bin/bash

# remove all existing keybindings
hc keyunbind --all


# ┌────────────────────┐
# │    Modifier Key    │
# └────────────────────┘
# Mod=Mod1  # Use alt as the main modifier
Mod=Mod4   # Use the super key as the main modifier



# ┌──────────────────────┐
# │    System Control    │
# └──────────────────────┘
hc keybind $Mod-Shift-q quit
hc keybind $Mod-Shift-r reload
hc keybind $Mod-Shift-c close

TERMINAL='urxvt'
hc keybind $Mod-Return spawn "${TERMINAL:-xterm}"


# ┌───────────────────┐
# │    Spawn dmenu    │
# └───────────────────┘
# Has a similar appearance to polybar
hc keybind $Mod-d spawn dmenu_run -h 36 -nb '#101215'


# ┌────────────────┐
# │    Movement    │
# └────────────────┘
hc keybind $Mod-Left  focus left
hc keybind $Mod-Down  focus down
hc keybind $Mod-Up  focus up
hc keybind $Mod-Right focus right
hc keybind $Mod-h   focus left
hc keybind $Mod-j   focus down
hc keybind $Mod-k   focus up
hc keybind $Mod-l   focus right


# ┌──────────────────┐
# │    Move Frame    │
# └──────────────────┘
hc keybind $Mod-Shift-Left  shift left
hc keybind $Mod-Shift-Down  shift down
hc keybind $Mod-Shift-Up  shift up
hc keybind $Mod-Shift-Right shift right
hc keybind $Mod-Shift-h   shift left
hc keybind $Mod-Shift-j   shift down
hc keybind $Mod-Shift-k   shift up
hc keybind $Mod-Shift-l   shift right


# ┌───────────────────┐
# │    Split Frame    │
# └───────────────────┘
# create an empty frame at the specified direction
hc keybind $Mod-u   split   bottom  0.5
hc keybind $Mod-o   split   right   0.5
# let the current frame explode into subframes
hc keybind $Mod-Control-space split explode


# ┌────────────────────┐
# │    Resize Frame    │
# └────────────────────┘
resizestep=0.02
hc keybind $Mod-Control-h   resize left +$resizestep
hc keybind $Mod-Control-j   resize down +$resizestep
hc keybind $Mod-Control-k   resize up +$resizestep
hc keybind $Mod-Control-l   resize right +$resizestep
hc keybind $Mod-Control-Left  resize left +$resizestep
hc keybind $Mod-Control-Down  resize down +$resizestep
hc keybind $Mod-Control-Up  resize up +$resizestep
hc keybind $Mod-Control-Right   resize right +$resizestep


# ┌─────────────┐
# │    Audio    │
# └─────────────┘
hc keybind XF86AudioMute  spawn amixer set Master toggle
hc keybind XF86AudioRaiseVolume spawn amixer set Master 1%+
hc keybind XF86AudioLowerVolume spawn amixer set Master 1%-


# ┌───────────────────┐
# │    Screenshots    │
# └───────────────────┘
# Ensure the directory exists
mkdir -p $HOME/Pictures/Screenshots
# Area Selection
hc keybind Print spawn scrot 'Pictures/Screenshots/%m-%d-%Y-%H%M%S.png' --select --exec 'notify-send --expire-time=2000 "Area Screenshot Saved."'
# Fullscreen
hc keybind Ctrl-Print spawn scrot 'Pictures/Screenshots/%m-%d-%Y-%H%M%S.png' --exec 'notify-send --expire-time=2000 "Fullscreen Screenshot Saved."'
# Focused Window
hc keybind Mod1-Print spawn scrot 'Pictures/Screenshots/%m-%d-%Y-%H%M%S.png' --focused --exec 'notify-send --expire-time=2000 "Window Screenshot Saved."'


# ┌─────────────────┐
# │    Backlight    │
# └─────────────────┘
hc keybind XF86MonBrightnessUp   spawn xbacklight +10
hc keybind XF86MonBrightnessDown spawn xbacklight -10


# ┌──────────────────┐
# │    Cycle Tags    │
# └──────────────────┘
hc keybind $Mod-period use_index +1 --skip-visible
hc keybind $Mod-comma  use_index -1 --skip-visible


# ┌──────────────┐
# │    Layout    │
# └──────────────┘
hc keybind $Mod-r remove
hc keybind $Mod-s floating toggle
hc keybind $Mod-f fullscreen toggle
hc keybind $Mod-Shift-f set_attr clients.focus.floating toggle
hc keybind $Mod-p pseudotile toggle

# The following cycles through the available layouts within a frame, but skips
# layouts, if the layout change wouldn't affect the actual window positions.
# I.e. if there are two windows within a frame, the grid layout is skipped.
hc keybind $Mod-space   \
  or , and . compare tags.focus.curframe_wcount = 2 \
  . cycle_layout +1 vertical horizontal max vertical grid  \
  , cycle_layout +1


# ┌─────────────┐
# │    Mouse    │
# └─────────────┘
hc mouseunbind --all
hc mousebind $Mod-Button1 move
hc mousebind $Mod-Button2 zoom
hc mousebind $Mod-Button3 resize

# (Browser Navigation)
hc mousebind Button8 xdotool alt+Left
hc mousebind Button9 xdotool alt+Right


# ┌─────────────┐
# │    Focus    │
# └─────────────┘
hc keybind $Mod-BackSpace   cycle_monitor
hc keybind $Mod-Tab   cycle_all +1
hc keybind $Mod-Shift-Tab   cycle_all -1
hc keybind $Mod-c cycle
hc keybind $Mod-i jumpto urgent