#!/bin/bash

# ┌────────────────────┐
# │    Multimonitor    │
# └────────────────────┘
# do multi monitor setup here, e.g.:
# hc set_monitors 1280x1024+0+0 1280x1024+1280+0
# or simply:
# hc detect_monitors