#!/bin/bash


# ┌───────────────────────┐
# │    Panel (Polybar)    │
# └───────────────────────┘
# # Try to load the custom panel script; falls back to the default one
panel=$HOME/.config/herbstluftwm/module/panel
[ -x "$panel" ] || panel=/etc/xdg/herbstluftwm/panel.sh
for monitor in $(hc list_monitors | cut -d: -f1) ; do
  # start it on each monitor
  "$panel" "$monitor" &
done


# ┌───────────────────────────┐
# │    Init Misc. Packages    │
# └───────────────────────────┘
# Start libinput-gestures
libinput-gestures-setup start

# Start dunst (responsible for notifications)
pgrep dunst || dunst &

# Start the network manager applet
nm-applet

# Prevent middle mouse pasting
xmousepasteblock

# Restore background
. $HOME/.fehbg

# Set amixer pre-amp to 40%
amixer set "Pre-Amp" '40%