#!/bin/bash

#  ┌────────────────────┐
#  │    Tag Creation    │
#  └────────────────────┘
tag_names=(     )
tag_keys=( {1..4} )

hc rename default "${tag_names[0]}" || true
for i in "${!tag_names[@]}" ; do
  hc add "${tag_names[$i]}"
  key="${tag_keys[$i]}"
  if ! [ -z "$key" ] ; then
    hc keybind "$Mod-$key" use_index "$i"
    hc keybind "$Mod-Shift-$key" move_index "$i"
  fi
done