#!/bin/sh

# Used for the addalias script (see $HOME/.dotfiles/scripts/addalias)
export ALIASES="$HOME/.dotfiles/aliases";

# Used for the sandbox script (see $HOME/.dotfiles/scripts/sandbox)
export SANDBOX="$HOME/OneDrive/Development/Sandbox/";

# Used for the layouts script (see $HOME/.dotfiles/scripts/layouts)
export LAYOUTDIR="$HOME/.dotfiles/layouts/"

# Used for the connect script (see $HOME/.dotfiles/scripts/ssh-util)
export SSHUTIL_DIR="/run/media/$USER/keys";

# Node Version Manager's directory
export NVM_DIR="$HOME/.nvm";