#!/bin/sh

# Used for the addalias script (see $HOME/.dotfiles/scripts/addalias)
export ALIASES="$HOME/.dotfiles/aliases";

# Used for the sandbox script (see $HOME/.dotfiles/scripts/sandbox)
export SANDBOX="$HOME/Dropbox/Development/Sandbox";

# Used for the connect script (see $HOME/.dotfiles/scripts/connect)
export SSHUTIL_DIR="/run/media/$USER/keys";

# Node Version Manager's directory
export NVM_DIR="$HOME/.nvm";
